[package]
name = "battle-city"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_rapier2d = "0.27"
bevy_ecs_ldtk = "0.10"
rand = "0.8.5"

[dependencies.bevy]
version = "0.14"
features = [
    "bmp",
]