[package]
name = "battle-city"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_rapier2d = "0.28"
bevy_ecs_ldtk = "0.11"
rand = "0.8.5"

[dependencies.bevy]
version = "0.15"
features = [
    "bmp",
]